<!--https://pixel-template.blogspot.com-->
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>IES Hispanidad</title>
    <script src="https://kit.fontawesome.com/61702239e8.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="views/css/style.css">
    <link rel="stylesheet" href="views/css/style_proyect.css">
</head>
<body>

<nav class="navbar">
    <div class="nav-left col-xs-12 col-sm-12 col-md-1 text-center mr-1">
        <a class="navbar-brand px-2 py-0" href="#">
            <img src="views/img/logos/logo.png" style="height: 57px; width: 125px; line-height: 55px;" alt="">
        </a>
    </div>
    <div class="nav-center d-flex mx-auto pl-sm-4 pl-md-4 pl-lg-4">

        <a class="navbar-brand px-2 py-0 text-light" href="index.php">
            Inicio
        </a>

        <div class="dropdown">
            <a class="navbar-brand px-2 py-0 text-light dropdown-toggle mr-0" id="centrosMenu" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                Centro
            </a>
            <div class="dropdown-menu" aria-labelledby="centrosMenu">
                <a class="dropdown-item" href="index.php?tutores">Tutores</a>
                <a class="dropdown-item" href="index.php?cursos">Cursos</a>
                <a class="dropdown-item" href="index.php?departamentos">Departamentos</a>
                <a class="dropdown-item" href="index.php?reglamento">Plan De Centro</a>
            </div>
        </div>

        <a class="navbar-brand px-0 py-0 m-0 pl-2 text-light" href="?proyectos">
            Proyectos
        </a>
    </div>

    <div class="nav-right d-flex col-xs-12 col-sm-12 col-md-icons">
        <div class="text-center mx-auto">
            <a class="navbar-brand p-0 mx-1 ml-2" href="https://es-es.facebook.com/ieshispanidad/">
                <img src="views/img/fontawesome/facebook.svg" height="30px" alt="">
            </a>
            <a class="navbar-brand p-0 mx-1" href="https://twitter.com/ies_hispanidad">
                <img src="views/img/fontawesome/twitter.svg" height="30px" alt="">
            </a>
            <a class="navbar-brand p-0 mx-1" href="https://www.instagram.com/ieshispanidad/">
                <img src="views/img/fontawesome/instagram.svg" height="30px" alt="">
            </a>
        </div>

    </div>
</nav>

<div class="container my-5">

    <hr class="w-100 m-0">
        <object data="views/pdf/Calendario_2022_2023.pdf" type="application/pdf">
            <embed src="views/pdf/Calendario_2022_2023.pdf" type="application/pdf">
        </object>

</div>


<footer class="footer row p-2">
    <div class="col-sm-12 col-md-6 d-flex">
        <img class="mx-auto foto-footer" src="views/img/logos/logo_ministerio.png" width="600px">
    </div>
    <!-- Copyright -->
    <div class="col-sm-12 col-md-6 d-flex">
        <div class="m-auto">
            © 2022 Copyright: <strong>I.E.S Hispanidad</strong>
        </div>
    </div>
    <!-- Copyright -->
</footer>
</body>
</html>