<!--https://pixel-template.blogspot.com-->
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>IES Hispanidad</title>
    <script src="https://kit.fontawesome.com/61702239e8.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <link rel="stylesheet" href="views/css/style.css">

    <style>

        .people-nearby .google-maps{
            background: #f8f8f8;
            border-radius: 4px;
            border: 1px solid #f1f2f2;
            padding: 20px;
            margin-bottom: 20px;
        }

        .people-nearby .google-maps .map{
            height: 300px;
            width: 100%;
            border: none;
        }

        .people-nearby .nearby-user{
            padding: 20px 0;
            border-top: 1px solid #f1f2f2;
            border-bottom: 1px solid #f1f2f2;
            margin-bottom: 20px;
        }

        img.profile-photo-lg{
            height: 80px;
            width: 80px;
            border-radius: 50%;
        }

        .col-user {
            width: fit-content !important;
        }

        @media only screen and (min-width: 700px) {
            .container {
                max-width: 90% !important;
            }

        }

    </style>

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css"
          media="screen">
    <script src="//cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
</head>
<body>

<nav class="navbar">
    <div class="nav-left col-xs-12 col-sm-12 col-md-1 text-center mr-1">
        <a class="navbar-brand px-2 py-0" href="#">
            <img src="views/img/logos/logo.png" style="height: 57px; width: 125px; line-height: 55px;" alt="">
        </a>
    </div>
    <div class="nav-center d-flex mx-auto pl-sm-4 pl-md-4 pl-lg-4">

        <a class="navbar-brand px-2 py-0 text-light" href="index.php">
            Inicio
        </a>

        <a class="navbar-brand px-0 py-0 m-0 pr-3 text-light" href="?proyectos">
            Proyectos
        </a>

        <div class="dropdown" style="cursor: pointer">
            <a class="navbar-brand px-2 py-0 text-light dropdown-toggle mr-0" id="centrosMenu" data-toggle="dropdown"
               aria-haspopup="true" aria-expanded="false">
                Centro
            </a>
            <div class="dropdown-menu" aria-labelledby="centrosMenu">
                <a class="dropdown-item" href="index.php?calendario">Calendario</a>
                <a class="dropdown-item" href="index.php?cursos">Cursos</a>
                <a class="dropdown-item" href="index.php?tutores">Tutores</a>
                <a class="dropdown-item" href="index.php?reglamento">Plan De Centro</a>
            </div>
        </div>

    </div>

    <div class="nav-right d-flex col-xs-12 col-sm-12 col-md-icons">
        <div class="text-center mx-auto">
            <a class="navbar-brand p-0 mx-1 ml-2" href="https://es-es.facebook.com/ieshispanidad/">
                <img src="views/img/fontawesome/facebook.svg" height="30px" alt="">
            </a>
            <a class="navbar-brand p-0 mx-1" href="https://twitter.com/ies_hispanidad">
                <img src="views/img/fontawesome/twitter.svg" height="30px" alt="">
            </a>
            <a class="navbar-brand p-0 mx-1" href="https://www.instagram.com/ieshispanidad/">
                <img src="views/img/fontawesome/instagram.svg" height="30px" alt="">
            </a>
        </div>

    </div>
</nav>

<div class="container">
    <div class="row">
        <div class="col-12 ">
            <div class="people-nearby row">

                <?php
                    $users = UserRepository::getUserByDepartament('lengua-literatura');

                    echo '<h3 class="col-12 my-4">LENGUA ESPAÑOLA Y LITERATURA</h3>';

                    foreach ($users as $user){
                        echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                    }

                $users = UserRepository::getUserByDepartament('geografia-historia');

                echo '<h3 class="col-12 my-4">GEOGRAFÍA E HISTORIA</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('ingles');

                echo '<h3 class="col-12 my-4">INGLÉS</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('frances');

                echo '<h3 class="col-12 my-4">FRANCÉS</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('cultura-clasica');

                echo '<h3 class="col-12 my-4">CULTURA CLÁSICA</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('filosofia');

                echo '<h3 class="col-12 my-4">FILOSOFÍA</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('economia');

                echo '<h3 class="col-12 my-4">ECONOMÍA</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('fol');

                echo '<h3 class="col-12 my-4">FOL</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('matematicas');

                echo '<h3 class="col-12 my-4">MATEMÁTICAS</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('biologia-geologia');

                echo '<h3 class="col-12 my-4">BIOLOGÍA Y GEOLOGÍA</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('fisica-quimica');

                echo '<h3 class="col-12 my-4">FÍSICA Y QUÍMICA</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('tecnologia');

                echo '<h3 class="col-12 my-4">TECNOLOGÍA</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('educacion-fisica');

                echo '<h3 class="col-12 my-4">EDUCACIÓN FÍSICA</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('musica');

                echo '<h3 class="col-12 my-4">MÚSICA</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('dibujo');

                echo '<h3 class="col-12 my-4">DIBUJO</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('orientacion');

                echo '<h3 class="col-12 my-4">ORIENTACIÓN</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('formacion-evaluacion');

                echo '<h3 class="col-12 my-4">FORMACIÓN, EVALUACIÓN E INNOVACIÓN EDUCATIVAS</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('relaciones-erasmus');

                echo '<h3 class="col-12 my-4">RELACIONES INTERNACIONALES Y ERASMUS +</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('imagen');

                echo '<h3 class="col-12 my-4">IMAGEN PERSONAL</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('electricidad-electronica');

                echo '<h3 class="col-12 my-4">ELECTRICIDAD Y ELECTRÓNICA</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('administracion');

                echo '<h3 class="col-12 my-4">ADMINISTRACIÓN</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                $users = UserRepository::getUserByDepartament('mecanica');

                echo '<h3 class="col-12 my-4">MECÁNICA DE VEHÍCULOS</h3>';

                foreach ($users as $user){
                    echo '<div class="nearby-user col-xl-3 col-md-4 col-sm-12 p-2">
                              <div class="row pt-1">
                                  <div class="col-user px-4">
                                      <img src="views/img/users/user.png" alt="user" class="profile-photo-lg">
                                  </div>
                                  <div class="col-user pt-2">
                                      <h5><a href="#" class="profile-link">'.$user->getFirstName().'</a></h5>
                                      <p>'.$user->getLastName().'</p>
                                  </div>
                              </div>
                          </div>';
                }

                ?>
            </div>
        </div>
    </div>
</div>

<footer class="footer row p-2">
    <div class="col-sm-12 col-md-6 d-flex">
        <img class="mx-auto foto-footer" src="views/img/logos/logo_ministerio.png" width="600px">
    </div>
    <!-- Copyright -->
    <div class="col-sm-12 col-md-6 d-flex">
        <div class="m-auto">
            © 2022 Copyright: <strong>I.E.S Hispanidad</strong>
        </div>
    </div>
    <!-- Copyright -->
</footer>
</body>
</html>